#!/bin/bash
# My first script

rails g model User username:string first_name:string last_name:string classroom:string

rails g model StreamMonitoring

rails g model PhysicalAssessment river_stream_name:string watershed_name:string names_of_investigators:string town:string latitude:string longitude:string site_description:string date:string time_of_sampling:string

rails g model WeatherToday clear_sunny:boolean overcast:boolean showers:boolean steady_rain:boolean heavy_rain:boolean

rails g model Weather48Hours clear_sunny:boolean overcast:boolean showers:boolean steady_rain:boolean heavy_rain:boolean

rails g model PhysicalAssessment approx_channel_width:string depth_a:string depth_b:string depth_c:string avg_depth:string stream_river_velocity_1:string stream_river_velocity_2:string avg_velocity:string bank_stability_right:string bank_stability_left:string overhead_canopy:string algal_growth:string pipes_into_river:boolean water_treatment_upstream:boolean

rails g model BottomComposition bedrock:string boulders:string cobble:string gravel:string sand_silt_clay:string organic_matter:string embededdness:string

rails g model RelativeFlow flow_slow_deep:boolean flow_slow_shallow:boolean flow_fast_deep:boolean flow_fast_shallow:boolean

rails g model WaterAppearance green:boolean tea:boolean milky:boolean muddy:boolean cloudy:boolean foamy:boolean clear:boolean reddish:boolean oily_sheen:boolean other:string

rails g model SurroundingLandUse dairy_farm:boolean park_area:boolean golf_course:boolean residential:boolean forest:boolean factory_mining:boolean other:string

rails g model RiparianBufferWidth buffer_width_left:string buffer_width_right:string

rails g model WaterOdor none:boolean rotten_eggs:boolean sewage:boolean fish:boolean oil:boolean chlorine:boolean other:string

rails g model BMITest

rails g model BMIPT1 stonefly_nymph:string mayfly_nymph:string caddis_fly_larvae:string dobsonfly_larvae:string riffle_beetle:string water_penny:string right_handed_snail:string number_of_taxa:string with_weighting_factors:string

rails g model BMIPT2 damselfly_nymph:string dragonfly_nymph:string sowbug:string scud:string crane_fly_larvae:string clams_mussels:string crayfish:string number_of_taxa:string with_weighting_factors:string

rails g model BMIPT3 midges:string black_fly_larvae:string planaria:string leech:stringnumber_of_taxa:string with_weighting_factors:string

rails g model BMIPT4 left_handed_snail:string aquatic_worms:string blood_midge:string rat_tailed_maggot:string number_of_taxa:string with_weighting_factors:string

rails g model OtherBiologicalIndicators native_mussels:string zebra_mussels:string rusty_crayfish:string aquatic_plants:string algae_cover:string diversity_index:string

rails g model ChemicalMonitoring

rails g model ChemTrial1 temperature:string ph:string turbidity:string orthophosphate:string dissolved_oxygen:string

rails g model ChemTrial2 temperature:string ph:string turbidity:string orthophosphate:string dissolved_oxygen:string field_notes:string

rails g model ChemAvg temperature:string ph:string turbidity:string orthophosphate:string dissolved_oxygen:string field_notes:string

rails g model SitePicture direction_taken:string label:string